apiVersion: v1
type: Opaque
kind: Secret
metadata:
  annotations:
    name: xml
  name: db-connection
  namespace: trading
data:
  db_connection: PD94bWwgdmVyc2lvbj0iMS4wIj8+Cjw/eG1sLXN0eWxlc2hlZXQgdHlwZT0idGV4dC94c2wiIGhyZWY9InJlbmRlci54c2wiPz4KPCFET0NUWVBFIHVpIFNZU1RFTSAiZGJfY29ubmVjdGlvbi5kdGQiPgo8IS0tIHBzcWwgLWggbG9jYWxob3N0IC1kIHRyYWRpbmdkYiAtVSB0cmFkaW5nIC0tPgo8ZGF0YWJhc2U+Cgk8dHlwZT5wb3N0Z3Jlc3FsPC90eXBlPgoJPGNvbm5lY3Rpb24+CgkJPGhvc3Q+MTcyLjE3LjAuMzwvaG9zdD4KCQk8ZGF0YWJhc2U+dHJhZGluZ2RiPC9kYXRhYmFzZT4KCQk8dXNlcm5hbWU+dHJhZGluZzwvdXNlcm5hbWU+CgkJPHBhc3N3b3JkPnRyYWRlPC9wYXNzd29yZD4KCTwvY29ubmVjdGlvbj4KPC9kYXRhYmFzZT4K
