#/bin/sh
# Insert AMEX Symbols
# Insert Stock Exchange
./symbol.py --exchange=AMEX
# Insert Stock Symbols
./symbol.py --exchange "AMEX" --symbol"AAMC" --name"Altisource Asset Management Corp"
./symbol.py --exchange "AMEX" --symbol"AAU" --name"Almaden Minerals Ltd"
./symbol.py --exchange "AMEX" --symbol"ACU" --name"Acme United Corp"
./symbol.py --exchange "AMEX" --symbol"ACY" --name"Aerocentury Corp"
./symbol.py --exchange "AMEX" --symbol"AE" --name"Adams Resources & Energy Inc"
./symbol.py --exchange "AMEX" --symbol"AGE" --name"Agex Therapeutics Inc"
./symbol.py --exchange "AMEX" --symbol"AIM" --name"Aim Immunotech Inc"
./symbol.py --exchange "AMEX" --symbol"AINC" --name"Ashford Inc"
./symbol.py --exchange "AMEX" --symbol"AIRI" --name"Air Industries Group"
./symbol.py --exchange "AMEX" --symbol"ALO" --name"Alio Gold Inc"
./symbol.py --exchange "AMEX" --symbol"AMPE" --name"Ampio Pharmaceuticals Inc"
./symbol.py --exchange "AMEX" --symbol"AMS" --name"American Shared Hospital Services"
./symbol.py --exchange "AMEX" --symbol"ANVS" --name"Annovis Bio Inc"
./symbol.py --exchange "AMEX" --symbol"APT" --name"Alpha Pro Tech"
./symbol.py --exchange "AMEX" --symbol"ARMP" --name"Armata Pharmaceuticals Inc"
./symbol.py --exchange "AMEX" --symbol"ASM" --name"Avino Silver & Gold Mines"
./symbol.py --exchange "AMEX" --symbol"ATNM" --name"Actinium Pharmaceuticals Inc"
./symbol.py --exchange "AMEX" --symbol"AUG" --name"Auryn Resources Incorporation"
./symbol.py --exchange "AMEX" --symbol"AUMN" --name"Golden Minerals Co"
./symbol.py --exchange "AMEX" --symbol"AWX" --name"Avalon Holdings Corp"
./symbol.py --exchange "AMEX" --symbol"AXU" --name"Alexco Resource Corp"
./symbol.py --exchange "AMEX" --symbol"BATL" --name"Battalion Oil Corp"
./symbol.py --exchange "AMEX" --symbol"BDL" --name"Flanigan'S Enterprises Inc"
./symbol.py --exchange "AMEX" --symbol"BDR" --name"Blonder Tongue Laboratories Inc"
./symbol.py --exchange "AMEX" --symbol"BGI" --name"Birks Group Inc"
./symbol.py --exchange "AMEX" --symbol"BHB" --name"Bar Harbour Bankshares"
./symbol.py --exchange "AMEX" --symbol"BIOX" --name"Bioceres Crop Solutions Corp"
./symbol.py --exchange "AMEX" --symbol"BKTI" --name"Bk Technologies Corporation"
./symbol.py --exchange "AMEX" --symbol"BRBS" --name"Blue Ridge Bankshares Inc (Va)"
./symbol.py --exchange "AMEX" --symbol"BRN" --name"Barnwell Industries Inc"
./symbol.py --exchange "AMEX" --symbol"BTG" --name"B2Gold Corp"
./symbol.py --exchange "AMEX" --symbol"BTN" --name"Ballantyne Strong Inc"
./symbol.py --exchange "AMEX" --symbol"BWL.A" --name"Bowl America Inc"
./symbol.py --exchange "AMEX" --symbol"CCF" --name"Chase Corp(Mass)"
./symbol.py --exchange "AMEX" --symbol"CEI" --name"Camber Energy Inc"
./symbol.py --exchange "AMEX" --symbol"CIX" --name"Compx International Inc"
./symbol.py --exchange "AMEX" --symbol"CKX" --name"Ckx Lands Inc"
./symbol.py --exchange "AMEX" --symbol"CMCL" --name"Caledonia Mining Corp Plc"
./symbol.py --exchange "AMEX" --symbol"CMT" --name"Core Molding Technologies Inc"
./symbol.py --exchange "AMEX" --symbol"COHN" --name"Cohen & Company Inc"
./symbol.py --exchange "AMEX" --symbol"CPHI" --name"China Pharma Hlgs Inc"
./symbol.py --exchange "AMEX" --symbol"CRHM" --name"Crh Medical Corp"
./symbol.py --exchange "AMEX" --symbol"CRMD" --name"Cormedix Inc"
./symbol.py --exchange "AMEX" --symbol"CTEK" --name"Cynergistek Inc"
./symbol.py --exchange "AMEX" --symbol"CTO" --name"Cto Realty Growth Inc"
./symbol.py --exchange "AMEX" --symbol"CVM" --name"Cel-Sci Corp"
./symbol.py --exchange "AMEX" --symbol"CVR" --name"Chicago Rivet & Machine Co"
./symbol.py --exchange "AMEX" --symbol"CVU" --name"Cpi Aerostructures"
./symbol.py --exchange "AMEX" --symbol"DIT" --name"Amcon Distributing Co"
./symbol.py --exchange "AMEX" --symbol"DLA" --name"Delta Apparel Inc"
./symbol.py --exchange "AMEX" --symbol"DNN" --name"Denison Mines Corporation"
./symbol.py --exchange "AMEX" --symbol"DPW" --name"Dpw Holdings Inc"
./symbol.py --exchange "AMEX" --symbol"DSS" --name"Document Securities Systems Inc"
./symbol.py --exchange "AMEX" --symbol"DXR" --name"Daxor Corp"
./symbol.py --exchange "AMEX" --symbol"ELA" --name"Envela Corporation"
./symbol.py --exchange "AMEX" --symbol"ELLO" --name"Ellomay Capital Ltd"
./symbol.py --exchange "AMEX" --symbol"ELMD" --name"Electromed Inc"
./symbol.py --exchange "AMEX" --symbol"EMAN" --name"Emagin Corp"
./symbol.py --exchange "AMEX" --symbol"EMX" --name"Emx Royalty Corporation"
./symbol.py --exchange "AMEX" --symbol"ENSV" --name"Enservco Corp"
./symbol.py --exchange "AMEX" --symbol"EPM" --name"Evolution Petroleum Corporation"
./symbol.py --exchange "AMEX" --symbol"EQX" --name"Equinox Gold Corp"
./symbol.py --exchange "AMEX" --symbol"ESP" --name"Espey Man & Electronics Corp"
./symbol.py --exchange "AMEX" --symbol"EVBN" --name"Evans Bancorp Inc"
./symbol.py --exchange "AMEX" --symbol"EVI" --name"Evi Industries Inc"
./symbol.py --exchange "AMEX" --symbol"FRD" --name"Friedman Industries Inc"
./symbol.py --exchange "AMEX" --symbol"FSI" --name"Flexible Solutions International In"
./symbol.py --exchange "AMEX" --symbol"FTSI" --name"Fts International Inc"
./symbol.py --exchange "AMEX" --symbol"GAU" --name"Galiano Gold Inc"
./symbol.py --exchange "AMEX" --symbol"GBR" --name"New Concept Energy Inc"
./symbol.py --exchange "AMEX" --symbol"GDP" --name"Goodrich Petroleum Corporation"
./symbol.py --exchange "AMEX" --symbol"GMO" --name"General Moly Inc"
./symbol.py --exchange "AMEX" --symbol"GORO" --name"Gold Resource Corporation"
./symbol.py --exchange "AMEX" --symbol"GPL" --name"Great Panther Mining Limited"
./symbol.py --exchange "AMEX" --symbol"GSAT" --name"Globalstar Inc"
./symbol.py --exchange "AMEX" --symbol"GSB" --name"Globalscape Inc"
./symbol.py --exchange "AMEX" --symbol"GSS" --name"Golden Star Resources Ltd"
./symbol.py --exchange "AMEX" --symbol"GSV" --name"Gold Standard Ventures Corp"
./symbol.py --exchange "AMEX" --symbol"GTE" --name"Gran Tierra Energy Inc"
./symbol.py --exchange "AMEX" --symbol"GV" --name"Goldfield Corp"
./symbol.py --exchange "AMEX" --symbol"HUSA" --name"Houston American Energy Corporation"
./symbol.py --exchange "AMEX" --symbol"IBIO" --name"Ibio Inc"
./symbol.py --exchange "AMEX" --symbol"IGC" --name"India Globalization Capital Inc"
./symbol.py --exchange "AMEX" --symbol"IMH" --name"Impac Mortgage Holdings Inc"
./symbol.py --exchange "AMEX" --symbol"IMO" --name"Imperial Oil"
./symbol.py --exchange "AMEX" --symbol"INDO" --name"Indonesia Energy Corp Ltd"
./symbol.py --exchange "AMEX" --symbol"INFU" --name"Infusystem Holdings Inc"
./symbol.py --exchange "AMEX" --symbol"INS" --name"Intelligent Systems Corp"
./symbol.py --exchange "AMEX" --symbol"INTT" --name"Intest Corp"
./symbol.py --exchange "AMEX" --symbol"INUV" --name"Inuvo Inc"
./symbol.py --exchange "AMEX" --symbol"ISDR" --name"Issuer Direct Corporation"
./symbol.py --exchange "AMEX" --symbol"ISR" --name"Isoray Inc"
./symbol.py --exchange "AMEX" --symbol"ITP" --name"It Tech Packaging Inc"
./symbol.py --exchange "AMEX" --symbol"JOB" --name"Gee Group Inc"
./symbol.py --exchange "AMEX" --symbol"KIQ" --name"Kelso Technologies"
./symbol.py --exchange "AMEX" --symbol"KLR" --name"Kaleyra Inc"
./symbol.py --exchange "AMEX" --symbol"LCTX" --name"Lineage Cell Therapeutics Inc"
./symbol.py --exchange "AMEX" --symbol"LEU" --name"Centrus Energy Corp"
./symbol.py --exchange "AMEX" --symbol"LGL" --name"Lgl Group Inc"
./symbol.py --exchange "AMEX" --symbol"LLEX" --name"Lilis Energy Inc"
./symbol.py --exchange "AMEX" --symbol"LNG" --name"Cheniere Energy Inc"
./symbol.py --exchange "AMEX" --symbol"LODE" --name"Comstock Mining Inc"
./symbol.py --exchange "AMEX" --symbol"MAG" --name"Mag Silver Corp"
./symbol.py --exchange "AMEX" --symbol"MCF" --name"Contango Oil & Gas Co"
./symbol.py --exchange "AMEX" --symbol"MHH" --name"Mastech Digital Inc"
./symbol.py --exchange "AMEX" --symbol"MLSS" --name"Milestone Scientific Inc"
./symbol.py --exchange "AMEX" --symbol"MMX" --name"Maverix Metals Inc"
./symbol.py --exchange "AMEX" --symbol"MSN" --name"Emerson Radio Corp"
./symbol.py --exchange "AMEX" --symbol"MTA" --name"Metalla Royalty & Streaming Ltd"
./symbol.py --exchange "AMEX" --symbol"MTNB" --name"Matinas Biopharma Holdings Inc"
./symbol.py --exchange "AMEX" --symbol"MXC" --name"Mexco Energy Corp"
./symbol.py --exchange "AMEX" --symbol"MYO" --name"Myomo Inc"
./symbol.py --exchange "AMEX" --symbol"NAK" --name"Northern Dynasty Minerals Ltd"
./symbol.py --exchange "AMEX" --symbol"NAVB" --name"Navidea Biopharmaceuticals Inc"
./symbol.py --exchange "AMEX" --symbol"NBY" --name"Novabay Pharmaceuticals Inc"
./symbol.py --exchange "AMEX" --symbol"NES" --name"Nuverra Environmental Solutions Inc"
./symbol.py --exchange "AMEX" --symbol"NG" --name"Novagold Resources Inc"
./symbol.py --exchange "AMEX" --symbol"NGD" --name"New Gold Inc"
./symbol.py --exchange "AMEX" --symbol"NHC" --name"National Health Care Corp"
./symbol.py --exchange "AMEX" --symbol"NNVC" --name"Nanoviricides Inc"
./symbol.py --exchange "AMEX" --symbol"NOG" --name"Northern Oil & Gas Inc (Nev)"
./symbol.py --exchange "AMEX" --symbol"NSPR" --name"Inspiremd Inc"
./symbol.py --exchange "AMEX" --symbol"NTIP" --name"Network-1 Technologies Inc"
./symbol.py --exchange "AMEX" --symbol"NTN" --name"Ntn Buzztime"
./symbol.py --exchange "AMEX" --symbol"NXE" --name"Nexgen Energy Ltd"
./symbol.py --exchange "AMEX" --symbol"OBLG" --name"Oblong Inc"
./symbol.py --exchange "AMEX" --symbol"OCX" --name"Oncocyte Corp"
./symbol.py --exchange "AMEX" --symbol"OGEN" --name"Oragenics Inc"
./symbol.py --exchange "AMEX" --symbol"PED" --name"Pedevco Corp"
./symbol.py --exchange "AMEX" --symbol"PFNX" --name"Pfenex Inc"
./symbol.py --exchange "AMEX" --symbol"PHGE" --name"Biomx Inc"
./symbol.py --exchange "AMEX" --symbol"PLAG" --name"Planet Green Holdings Corp"
./symbol.py --exchange "AMEX" --symbol"PLG" --name"Platinum Group Metals Ltd"
./symbol.py --exchange "AMEX" --symbol"PLM" --name"Polymet Mining Cp"
./symbol.py --exchange "AMEX" --symbol"PLX" --name"Protalix Biotherapeutics Inc"
./symbol.py --exchange "AMEX" --symbol"PRK" --name"Park National Corp"
./symbol.py --exchange "AMEX" --symbol"PTN" --name"Palatin Technologies Inc"
./symbol.py --exchange "AMEX" --symbol"PZG" --name"Paramount Gold Nevada Corp"
./symbol.py --exchange "AMEX" --symbol"REI" --name"Ring Energy Inc"
./symbol.py --exchange "AMEX" --symbol"RLGT" --name"Radiant Logistics Inc"
./symbol.py --exchange "AMEX" --symbol"RVP" --name"Retractable Technologies Inc"
./symbol.py --exchange "AMEX" --symbol"SDI" --name"Standard Diversified Inc"
./symbol.py --exchange "AMEX" --symbol"SDPI" --name"Superior Drilling Products Inc"
./symbol.py --exchange "AMEX" --symbol"SEB" --name"Seaboard Corp Delaware"
./symbol.py --exchange "AMEX" --symbol"SENS" --name"Senseonics Holdings Inc"
./symbol.py --exchange "AMEX" --symbol"SIF" --name"Sifco Industries Inc"
./symbol.py --exchange "AMEX" --symbol"SILV" --name"Silvercrest Metals Inc"
./symbol.py --exchange "AMEX" --symbol"SMTS" --name"Sierra Metals Inc"
./symbol.py --exchange "AMEX" --symbol"SSY" --name"Sunlink Health Systems Inc"
./symbol.py --exchange "AMEX" --symbol"STXS" --name"Stereotaxis Inc"
./symbol.py --exchange "AMEX" --symbol"SVM" --name"Silvercorp Metals Inc"
./symbol.py --exchange "AMEX" --symbol"SVT" --name"Servotronics Inc"
./symbol.py --exchange "AMEX" --symbol"SYN" --name"Synthetic Biologics Inc"
./symbol.py --exchange "AMEX" --symbol"TAT" --name"Transatlantic Petroleum Ltd"
./symbol.py --exchange "AMEX" --symbol"TGB" --name"Taseko Mines"
./symbol.py --exchange "AMEX" --symbol"TGC" --name"Tengasco"
./symbol.py --exchange "AMEX" --symbol"THM" --name"International Tower Hill Mines"
./symbol.py --exchange "AMEX" --symbol"TKAT" --name"Takung Art Co Ltd"
./symbol.py --exchange "AMEX" --symbol"TMBR" --name"Timber Pharmaceuticals Inc"
./symbol.py --exchange "AMEX" --symbol"TMP" --name"Tompkins Financial Corporation"
./symbol.py --exchange "AMEX" --symbol"TMQ" --name"Trilogy Metals Inc New"
./symbol.py --exchange "AMEX" --symbol"TPHS" --name"Trinity Pl Hldgs Inc"
./symbol.py --exchange "AMEX" --symbol"TRT" --name"Trio-Tech International"
./symbol.py --exchange "AMEX" --symbol"TRX" --name"Tanzanian Gold Corporation"
./symbol.py --exchange "AMEX" --symbol"TRXC" --name"Transenterix Inc"
./symbol.py --exchange "AMEX" --symbol"UAMY" --name"United States Antimony Corp"
./symbol.py --exchange "AMEX" --symbol"UAVS" --name"Ageagle Aerial Systems Inc"
./symbol.py --exchange "AMEX" --symbol"UEC" --name"Uranium Energy Corp"
./symbol.py --exchange "AMEX" --symbol"UFAB" --name"Unique Fabricating"
./symbol.py --exchange "AMEX" --symbol"URG" --name"Ur Energy Inc"
./symbol.py --exchange "AMEX" --symbol"USAS" --name"Americas Gold & Silver Corporation"
./symbol.py --exchange "AMEX" --symbol"UUU" --name"Universal Security Instruments Inc"
./symbol.py --exchange "AMEX" --symbol"UUUU" --name"Energy Fuels Inc"
./symbol.py --exchange "AMEX" --symbol"VGZ" --name"Vista Gold Corp"
./symbol.py --exchange "AMEX" --symbol"VHC" --name"Virnetx Holding Corp"
./symbol.py --exchange "AMEX" --symbol"VNRX" --name"Volitionrx Limited"
./symbol.py --exchange "AMEX" --symbol"VOLT" --name"Volt Information Sciences Inc"
./symbol.py --exchange "AMEX" --symbol"WRN" --name"Western Copper & Gold Corp"
./symbol.py --exchange "AMEX" --symbol"WTT" --name"Wireless Telecom Group Inc"
./symbol.py --exchange "AMEX" --symbol"WYY" --name"Widepoint Corp"
./symbol.py --exchange "AMEX" --symbol"XPL" --name"Solitario Zinc Corp"
./symbol.py --exchange "AMEX" --symbol"XTNT" --name"Xtant Medical Hldgs Inc"
./symbol.py --exchange "AMEX" --symbol"XXII" --name"22Nd Century Group Inc"
./symbol.py --exchange "AMEX" --symbol"YCBD" --name"Cbdmd Inc"
./symbol.py --exchange "AMEX" --symbol"ZDGE" --name"Zedge Inc"
./symbol.py --exchange "AMEX" --symbol"ZOM" --name"Zomedica Pharmaceuticals Corp"
./symbol.py --exchange "AMEX" --symbol"BCV-A" --name"Bancroft Fund Ltd 5.375% Pfd Cum Ser A"
./symbol.py --exchange "AMEX" --symbol"BRG-A" --name"Bluerock Residential Growth Reit Redeemable Pfd Ser A %"
./symbol.py --exchange "AMEX" --symbol"BRG-C" --name"Bluerock Residential Growth Reit 7.625% Cum Red Pref 19/07/2021 C"
./symbol.py --exchange "AMEX" --symbol"BRG-D" --name"Bluerock Residential Growth Reit Pfd Ser D"
./symbol.py --exchange "AMEX" --symbol"ECF-A" --name"Ellsworth Growth And Income Fund Lt 5.25% Cum Pfd Shs Series A Usd25"
./symbol.py --exchange "AMEX" --symbol"GGN-B" --name"Gamco Global Gold Nat Res & Income 5% Pref Ser 'B' Usd25"
./symbol.py --exchange "AMEX" --symbol"GGO-A" --name"Gabelli Go Anywhere Trust Cum Puttable & Call Pfd Ser A"
./symbol.py --exchange "AMEX" --symbol"GLU-A" --name"Gabelli Global Utility & Income Tr 6% Cum Pref A(Put&Call)"
./symbol.py --exchange "AMEX" --symbol"GLU-B" --name"Gabelli Global Utility & Income Tr Cum Puttable And Callable Pfd Shs Ser B"
./symbol.py --exchange "AMEX" --symbol"HLM-" --name"Hillman Group Capital Trust 11.6% Trust Pfd Usd25"
./symbol.py --exchange "AMEX" --symbol"HWM-" --name"Howmet Aerospace Inc $3.75 Preferred Stock"
./symbol.py --exchange "AMEX" --symbol"IPB" --name"Indexplus Trust 6.0518% Prf 15/5/33 Usd25"
./symbol.py --exchange "AMEX" --symbol"PCG-A" --name"Pacific Gas & Electric Co 6% 1St Cum Red Pfd Usd25"
./symbol.py --exchange "AMEX" --symbol"PCG-B" --name"Pacific Gas & Electric Co 5 1/2% 1St Cum Pfd Usd25"
./symbol.py --exchange "AMEX" --symbol"PCG-C" --name"Pacific Gas & Electric Co 5% 1St Cum Pfd Usd25"
./symbol.py --exchange "AMEX" --symbol"PCG-D" --name"Pacific Gas & Electric Co 5% 1St Cum Red Pfd Usd25"
./symbol.py --exchange "AMEX" --symbol"PCG-E" --name"Pacific Gas & Electric Co 5% 1St Cum Red'A'Pfd Usd25"
./symbol.py --exchange "AMEX" --symbol"PCG-G" --name"Pacific Gas & Electric Co 4.80% 1St Cum Red Pfd Usd25"
./symbol.py --exchange "AMEX" --symbol"PCG-H" --name"Pacific Gas & Electric Co 4.50% 1St Cum Red Pfd Usd25"
./symbol.py --exchange "AMEX" --symbol"PCG-I" --name"Pacific Gas & Electric Co 4.36% 1St Cum Red Pfd Usd25"
./symbol.py --exchange "AMEX" --symbol"PLYM-A" --name"Plymouth Industrial Reit Inc 7.50% Cum Red Pref Shs Series A Usd25"
./symbol.py --exchange "AMEX" --symbol"PW-A" --name"Power Reit 7.75% Cum Red Perp Pfd Shs Ser A Usd25"
./symbol.py --exchange "AMEX" --symbol"RHE-A" --name"Regional Health Properties Inc 10.875% Cum Red Prefd Stock Usd25"
./symbol.py --exchange "AMEX" --symbol"SACC" --name"Sachem Capital Corp 6.875% Nts 30/12/2024 Usd25.00"
./symbol.py --exchange "AMEX" --symbol"SCE-B" --name"Southern California Edison Co 4.08% Cum Pfd Usd25"
./symbol.py --exchange "AMEX" --symbol"SCE-C" --name"Southern California Edison Co 4.24% Cum Pfd Usd25"
./symbol.py --exchange "AMEX" --symbol"SCE-D" --name"Southern California Edison Co 4.32% Cum Pfd Usd25"
./symbol.py --exchange "AMEX" --symbol"SCE-E" --name"Southern California Edison Co 4.78% Cum Pfd Usd25"
./symbol.py --exchange "AMEX" --symbol"YCBD-A" --name"Cbdmd Inc 8% Series A Cum Convert Pfd Stk Usd25"
