---
- hosts: localhost
  vars:
    password: "{{ lookup('password', '/dev/null chars=ascii_letters,digits length=64') }}"
  tasks:
  - set_fact:
      xml: "{{ lookup('file', './files/db_connection.xml') | replace('PASSWORD', password) }}"
  - name: appending xml secret to db_connection
    lineinfile:
      path: ../k8s/1_db_connection.yml
      line: "  db_connection: {{ xml | b64encode }}"
      insertbefore: EOF
